config/routes.rb
VisFig::Application.routes.draw do
  resources :figures

  resources :visualisations

  resources :data

  root :to => 'home#show'

end

app/models/figure.rb
class Figure < ActiveRecord::Base

  belongs_to :visualisation
  attr_accessible :columnHeadings, :dataSet, :doi, :title, :visualisation

end

app/models/visualisation.rb
class Visualisation < ActiveRecord::Base
  attr_accessible :description, :libLocation, :libName, :maxNoOfParameters, :minNoOfParameters

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/figures_controller.rb
class FiguresController < ApplicationController
  # GET /figures
  # GET /figures.json
  require 'open-uri'
  require 'json'
  def index
    @figures = Figure.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @figures }
    end
  end

  # GET /figures/1
  # GET /figures/1.json
  def show
    @figure = Figure.find(params[:id])
    if !@figure.dataSet.nil?
      @dataset = open(@figure.dataSet).read
      if !@dataset.nil?
        @parsed_data = JSON.parse @dataset
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @figure }
    end
  end

  # GET /figures/new
  # GET /figures/new.json
  def new
    @figure = Figure.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @figure }
    end
  end

  # GET /figures/1/edit
  def edit
    @figure = Figure.find(params[:id])
  end

  # POST /figures
  # POST /figures.json
  def create
    parameters = params[:figure]
    visualisation = parameters.delete(:visualisation)
    @figure = Figure.new(parameters)
    @figure.visualisation = Visualisation.find(visualisation)

    respond_to do |format|
      if @figure.save
        format.html { redirect_to @figure, notice: 'Figure was successfully created.' }
        format.json { render json: @figure, status: :created, location: @figure }
      else
        format.html { render action: "new" }
        format.json { render json: @figure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /figures/1
  # PUT /figures/1.json
  def update
    @figure = Figure.find(params[:id])

    respond_to do |format|
      if @figure.update_attributes(params[:figure])
        format.html { redirect_to @figure, notice: 'Figure was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @figure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /figures/1
  # DELETE /figures/1.json
  def destroy
    @figure = Figure.find(params[:id])
    @figure.destroy

    respond_to do |format|
      format.html { redirect_to figures_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/visualisations_controller.rb
class VisualisationsController < ApplicationController
  # GET /visualisations
  # GET /visualisations.json
  def index
    @visualisations = Visualisation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visualisations }
    end
  end

  # GET /visualisations/1
  # GET /visualisations/1.json
  def show
    @visualisation = Visualisation.find(params[:id])
    @figure = Figure.new
    @figure.visualisation = @visualisation
    @figure.title = "figure of #{@visualisation.libName}"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visualisation }
    end
  end

  # GET /visualisations/new
  # GET /visualisations/new.json
  def new
    @visualisation = Visualisation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visualisation }
    end
  end

  # GET /visualisations/1/edit
  def edit
    @visualisation = Visualisation.find(params[:id])
  end

  # POST /visualisations
  # POST /visualisations.json
  def create
    @visualisation = Visualisation.new(params[:visualisation])

    respond_to do |format|
      if @visualisation.save
        format.html { redirect_to @visualisation, notice: 'Visualisation was successfully created.' }
        format.json { render json: @visualisation, status: :created, location: @visualisation }
      else
        format.html { render action: "new" }
        format.json { render json: @visualisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visualisations/1
  # PUT /visualisations/1.json
  def update
    @visualisation = Visualisation.find(params[:id])

    respond_to do |format|
      if @visualisation.update_attributes(params[:visualisation])
        format.html { redirect_to @visualisation, notice: 'Visualisation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visualisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visualisations/1
  # DELETE /visualisations/1.json
  def destroy
    @visualisation = Visualisation.find(params[:id])
    @visualisation.destroy

    respond_to do |format|
      format.html { redirect_to visualisations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/figures_helper.rb
module FiguresHelper
end

app/helpers/visualisations_helper.rb
module VisualisationsHelper
end

app/views/figures/_form.html.erb
<%= form_for(@figure) do |f| %>
  <% if @figure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@figure.errors.count, "error") %> prohibited this figure from being saved:</h2>

      <ul>
      <% @figure.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :doi %><br />
    <%= f.text_field :doi %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :dataSet %><br />
    <%= f.text_field :dataSet %>
  </div>
  <div class="field">
    <%= f.label :columnHeadings %><br />
    <%= f.text_area :columnHeadings %>
  </div>
  <div class="field">
    <%= f.label :visualisation %><br />
    <%= f.text_field :visualisation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/figures/edit.html.erb
<h1>Editing figure</h1>

<%= render 'form' %>

<%= link_to 'Show', @figure %> |
<%= link_to 'Back', figures_path %>

app/views/figures/index.html.erb
<h1>Listing figures</h1>

<table>
  <tr>
    <th>Doi</th>
    <th>Title</th>
    <th>Dataset</th>
    <th>Columnheadings</th>
    <th>Visualisation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @figures.each do |figure| %>
  <tr>
    <td><%= figure.doi %></td>
    <td><%= figure.title %></td>
    <td><%= figure.dataSet %></td>
    <td><%= figure.columnHeadings %></td>
    <td><%= figure.visualisation %></td>
    <td><%= link_to 'Show', figure %></td>
    <td><%= link_to 'Edit', edit_figure_path(figure) %></td>
    <td><%= link_to 'Destroy', figure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Figure', new_figure_path %>

app/views/figures/new.html.erb
<h1>New figure</h1>

<%= render 'form' %>

<%= link_to 'Back', figures_path %>

app/views/figures/show.html.erb
<script type="text/javascript">
    alert('yolo');
    var url = <%= @figure.dataSet %>;

    alert('yo');
    plotFromFigshare(url);
    alert('lo');

    function plotFromFigshare(url) {
        var chartOptions = {};

        var fsAPI = url;//"http://api.figshare.com/v1/articles/10.6084/m9.figshare.889719";
        $.getJSON( fsAPI, {
            tags: "figshare",
            tagmode: "any",
            format: "json"
        })
                .done(function( data ) {
                    var csvurl = data.items[0].files[0].download_url.replace("http://","");
                    $.get("http://www.corsproxy.com/"+csvurl, function(csvdata) {

                        var xhead = 'Year';
                        var yhead = 'Total Body Count';
                        var parsed = parseCSV(csvdata, xhead, yhead, true);

                        var options = setupOptions("Body count in films by year", "Year", "Total Body Count");
                        options.xAxis.categories = parsed.x;
                        options.series[0] = parsed.y;

                        var chart = new Highcharts.Chart(options);

                    });
                });
    }

    function setupOptions(title, xlabel, ylabel) {
        var options = {
            chart: {
                renderTo: 'result',
                type: 'column'
            },
            title: {
                text: title
            },
            xAxis: {
                categories: []
            },
            yAxis: {
                title: {
                    text: ylabel
                }
            },
            series: []
        }
        return options;
    }

    function parseCSV(csvstring, xHeader, yHeader, aggregateY) {
        var parsed = {};
        var xCategories = [];
        var ySeries = {name: yHeader, data:[]};

        var data = d3.csv.parse(csvstring);
        var nested = [];

        if(aggregateY) {
            var aggHeader = "Total_"+yHeader;
            var rolled = {};
            rolled[aggHeader] = "";
            nested = d3.nest().key(function(d) { return d[xHeader]; }).sortKeys(d3.ascending).rollup(function(leaves) {
                rolled[aggHeader] = d3.sum(leaves, function(d) {
                    return parseFloat(d[yHeader]);
                });
                return rolled[aggHeader];
            })
                    .entries(data);
        }
        else {
            $.each(d3.entries(data), function(index, value) {
                console.log(JSON.stringify(value));
                var barObj = {};
                barObj.key = value.value[xHeader];
                barObj.values = value.value[yHeader];
                nested.push(barObj);
            });
        }

        $.each(nested, function(index, value) {
            xCategories.push(value.key);
            ySeries.data.push(value.values);
        });

        parsed.x = xCategories;
        parsed.y = ySeries;
        console.log(JSON.stringify(parsed));
        return parsed;
    }


</script>

<p id="notice"><%= notice %></p>

<p>
  <b>Doi:</b>
  <%= @figure.doi %>
</p>

<p>
  <b>Title:</b>
  <%= @figure.title %>
</p>

<p>
  <b>Dataset:</b>
  <%= @figure.dataSet %>
</p>

<p>
  <b>Columnheadings:</b>
  <%= @figure.columnHeadings %>
</p>

<p>
  <b>Visualisation:</b>
  <%= @figure.visualisation.libName %>
</p>

<%= @parsed_data.keys %>

<%= link_to "Generated using this visualisation", @figure.visualisation %> <br>


<%= link_to 'Edit', edit_figure_path(@figure) %> |
<%= link_to 'Back', figures_path %>

app/views/home/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>VisFig</title>
</head>

<body>
<div class="container">
  <div class="starter-template">
    <h1>VisFig</h1>

    <p class="lead">Welcome to VisFig! Simple and sleek way to reproduce other's figure using your own datasets. </p>

    <p> All you need is the URL to your dataset and you are ready to go! Select a visualisation, pop in a link to your dataset, and generate beautiful interactive graphs. </p>
  </div>

  <table style="width:100%">
    <tr >
      <th><h2 style="">Visualisation</h2></th>
      <th><h2>Data Description</h2></th>
    </tr>
    <tr style="height:300px">
      <td><h4>
        <%= link_to "Bar Chart", visualisation_url(1)%>
      </h4>
        <%= image_tag 'bar_chart.png', :style => "width:300px" %>
      </td>
      <td class="col-lg-6">
        <p>
        <h5> On-screen movie kill counts for hundreds of films</h5>
        Original dataset from: Olson, Randy (2013): On-screen movie kill counts for hundreds of films. figshare.
        http://dx.doi.org/10.6084/m9.figshare.889719 <br/>
        </p>
      </td>
    </tr>

    <tr style="height:300px">
      <td><h4><a href="figshare.html">Area Charts</a></h4>
        <%= image_tag 'area_chart.png', :style => "width:300px" %>
      </td>
      <td class="col-lg-6"><p><h5>Browser market shares of a specific website, 2010</h5>
        Original plot and dataset from <a href="http://www.highcharts.com/demo/pie-gradient"> HighCharts</a>. Have other marketing and performance data and want to visualise it? Try out VisFig and get the area chart as pretty as this one.
        </p></td>
    </tr>

    <tr style="height:300px">
      <td><h4><a href="figshare.html">Chart Diagram</a></h4>
        <%= image_tag 'pie_chart.png', :style => "width:300px" %>
      </td>
      <td class="col-lg-6">Original plot and dataset from <a href="http://www.highcharts.com/demo/pie-gradient"> HighCharts</a>. Have other marketing and performance dataand want to visualise it? Try out VisFig and get the area chartas\
        prettyas thisone.</td>
    </tr>
  </table>
</div>



<div id="footer">
  <p>

  </p>
</div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VisFig</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag 'jquery'%>
  <%= javascript_include_tag 'd3.min.js'%>
  <%= javascript_include_tag 'highcharts.js'%>

  <%= csrf_meta_tags %>
</head>

<body>
<%= nav_bar :fixed => :top, :brand => "VisFig", :responsive => true do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <%= menu_divider %>
        <%= drop_down "Visualisations" do %>
            <%= menu_item "Bar Charts", visualisations_path %>
        <% end %>
        <%= menu_item "Gallery", figures_path %>
    <% end %>
<% end %>

<%= bootstrap_flash %>

<div class="container" style="margin-top: 50px">
<%= yield %>
</div>

</body>
</html>

app/views/visualisations/_form.html.erb
<%= form_for(@visualisation) do |f| %>
  <% if @visualisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visualisation.errors.count, "error") %> prohibited this visualisation from being saved:</h2>

      <ul>
      <% @visualisation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :libName %><br />
    <%= f.text_area :libName %>
  </div>
  <div class="field">
    <%= f.label :libLocation %><br />
    <%= f.text_area :libLocation %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :minNoOfParameters %><br />
    <%= f.number_field :minNoOfParameters %>
  </div>
  <div class="field">
    <%= f.label :maxNoOfParameters %><br />
    <%= f.number_field :maxNoOfParameters %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visualisations/edit.html.erb
<h1>Editing visualisation</h1>

<%= render 'form' %>

<%= link_to 'Show', @visualisation %> |
<%= link_to 'Back', visualisations_path %>

app/views/visualisations/index.html.erb
<h1>Listing visualisations</h1>

<table>
  <tr>
    <th>Libname</th>
    <th>Liblocation</th>
    <th>Description</th>
    <th>Minnoofparameters</th>
    <th>Maxnoofparameters</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @visualisations.each do |visualisation| %>
  <tr>
    <td><%= visualisation.libName %></td>
    <td><%= visualisation.libLocation %></td>
    <td><%= visualisation.description %></td>
    <td><%= visualisation.minNoOfParameters %></td>
    <td><%= visualisation.maxNoOfParameters %></td>
    <td><%= link_to 'Show', visualisation %></td>
    <td><%= link_to 'Edit', edit_visualisation_path(visualisation) %></td>
    <td><%= link_to 'Destroy', visualisation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Visualisation', new_visualisation_path %>

app/views/visualisations/new.html.erb
<h1>New visualisation</h1>

<%= render 'form' %>

<%= link_to 'Back', visualisations_path %>

app/views/visualisations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Libname:</b>
  <%= @visualisation.libName %>
</p>

<p>
  <b>Liblocation:</b>
  <%= @visualisation.libLocation %>
</p>

<p>
  <b>Description:</b>
  <%= @visualisation.description %>
</p>

<p>
  <b>Minnoofparameters:</b>
  <%= @visualisation.minNoOfParameters %>
</p>

<p>
  <b>Maxnoofparameters:</b>
  <%= @visualisation.maxNoOfParameters %>
</p>


<div class="container">


  <%= form_for @figure do |f| %>
    Give it a title <%= f.text_field :title %>                                                                                     <br>
    Dataset URL: <%= f.text_field :dataSet, :value => "http://api.figshare.com/v1/articles/10.6084/m9.figshare.889719" %><br>
    Column Headings
      <%= f.text_field :columnHeadings %>
      <%= f.submit 'Vis me a fig', :class => "btn btn-lg btn-success" %>
      <%= f.hidden_field :visualisation, :value => @visualisation.id %>
  <% end %>

  <%= link_to 'Edit', edit_visualisation_path(@visualisation) %> |
  <%= link_to 'Back', visualisations_path %>

</div>